(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const DRAFTS='afaqNewsDrafts', SITE_URL_KEY='afaqNewsSiteUrl';
  const langs=['en','ar','zh']; let articles=[];let editingId=null;let imageData=null;let imageName='';
  const countries=()=>Array.isArray(window.AFAQ_COUNTRIES)?window.AFAQ_COUNTRIES:[];
  const isLocalAdmin=()=>['localhost','127.0.0.1'].includes(location.hostname);
  const siteUrl=()=>localStorage.getItem(SITE_URL_KEY)||'';
  const apiUrl=()=>{const base=isLocalAdmin()?siteUrl():location.origin;return `${String(base).replace(/\/$/,'')}/api/news-admin`};
  const saveState=m=>{const e=$('#saveState');if(e)e.textContent=m;};
  const api=async(action,payload={})=>{const url=apiUrl();if(!url||url.endsWith('/api/news-admin')&&isLocalAdmin()&&!siteUrl())throw new Error('Add your public Netlify site URL in Admin Settings first.');const r=await fetch(url,{method:action==='get'?'GET':'POST',headers:{'Content-Type':'application/json'},body:action==='get'?undefined:JSON.stringify({action,...payload})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j};
  function loadDrafts(){try{articles=JSON.parse(localStorage.getItem(DRAFTS)||'[]');if(!Array.isArray(articles))articles=[]}catch{articles=[]}}
  function saveDrafts(){localStorage.setItem(DRAFTS,JSON.stringify(articles));saveState('Saved locally');}
  function localizedCountry(name,lang){const m={'Palestine – West Bank':{ar:'فلسطين – الضفة الغربية',zh:'巴勒斯坦—约旦河西岸'},'Palestine – Gaza':{ar:'فلسطين – غزة',zh:'巴勒斯坦—加沙'},'Yemen – Aden':{ar:'اليمن – عدن',zh:'也门—亚丁'},"Yemen – Sana'a":{ar:'اليمن – صنعاء',zh:'也门—萨那'}};return m[name]?.[lang]||name;}
  function fillCountries(){const s=$('#countryCode');s.innerHTML=countries().map(c=>`<option value="${esc(c.code)}">${esc(c.name)}</option>`).join('');const f=$('#adminCountryFilter');f.innerHTML='<option value="">All markets</option>'+countries().map(c=>`<option value="${esc(c.code)}">${esc(c.name)}</option>`).join('');}
  function switchView(name){$$('.adminView').forEach(v=>v.classList.add('hidden'));$(`#view${name[0].toUpperCase()+name.slice(1)}`)?.classList.remove('hidden');$$('.adminSide nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#adminHeading').textContent=name==='dashboard'?'News Dashboard':name==='editor'?(editingId?'Edit article':'Create article'):name==='articles'?'All Articles':name==='media'?'Media Library':'Admin Settings';if(name==='dashboard')renderDashboard();if(name==='articles')renderList();if(name==='media')renderMedia();}
  function renderDashboard(){const pub=articles.filter(a=>a.status==='published').length,draft=articles.filter(a=>a.status!=='published').length,feat=articles.filter(a=>a.featured).length,markets=new Set(articles.map(a=>a.countryCode).filter(Boolean)).size;$('#statPublished').textContent=pub;$('#statDrafts').textContent=draft;$('#statFeatured').textContent=feat;$('#statCountries').textContent=markets;$('#recentList').innerHTML=articles.slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,8).map(row).join('')||'<div class="newsEmpty">No articles yet. Create your first regulatory update.</div>';}
  function translationStatus(a){return langs.map(l=>{const ok=!!(a.title?.[l]&&a.body?.[l]);return `<span class="translationChip ${ok?'ok':'missing'}">${l.toUpperCase()} ${ok?'✓':'!'}</span>`}).join('')}
  function row(a){const title=a.title?.en||'Untitled article';return `<div class="articleRow"><div>${a.image?`<img class="articleThumb" src="${esc(a.image)}" alt="">`:'<div class="articleThumb"></div>'}</div><div class="articleRowMain"><h3>${esc(title)}</h3><p>${esc(a.country||a.countryCode||'')} · ${esc(a.date||'')} · <span class="status ${a.status==='published'?'published':'draft'}">${esc(a.status||'draft')}</span> ${a.impact?`· <span class="impactMini ${esc(a.impact)}">${esc(a.impact)}</span>`:''}</p><div class="translationChips">${translationStatus(a)}</div></div><div class="rowActions"><button data-edit="${esc(a.id)}">Edit</button>${a.status==='published'?`<button data-open="${esc(a.slug)}">Open</button>`:''}<button data-delete="${esc(a.id)}">Delete</button></div></div>`}
  function renderList(){const q=($('#adminSearch')?.value||'').toLowerCase(),c=$('#adminCountryFilter')?.value||'',s=$('#adminStatusFilter')?.value||'';const list=articles.filter(a=>!c||a.countryCode===c).filter(a=>!s||a.status===s).filter(a=>!q||[a.title?.en,a.title?.ar,a.title?.zh,a.country,a.authority,a.category?.en,(a.products||[]).join(' ')].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));$('#articleList').innerHTML=list.map(row).join('')||'<div class="newsEmpty">No matching articles.</div>';}
  function renderMedia(){const seen=new Map();articles.filter(a=>a.status==='published'&&a.image).forEach(a=>{if(!seen.has(a.image))seen.set(a.image,a)});$('#mediaGrid').innerHTML=[...seen.entries()].map(([src,a])=>`<div class="mediaItem"><img src="${esc(src)}" alt=""><div><b>${esc(a.title?.en||'')}</b><small>${esc(a.country||'')}</small><button data-media-copy="${esc(src)}">Copy path</button></div></div>`).join('')||'<div class="newsEmpty">No published images yet.</div>';}
  async function sync(){try{const r=await api('get');const drafts=articles.filter(a=>a.status==='draft');const remote=r.articles||[];const remoteIds=new Set(remote.map(a=>a.id));articles=[...remote,...drafts.filter(a=>!remoteIds.has(a.id))];saveState(`Synced · ${remote.length} published articles`);renderDashboard();renderList();renderMedia();}catch(e){saveState('Sync failed');$('#apiStatus').textContent=e.message;}}
  function clearEditor(){editingId=null;imageData=null;imageName='';$('#articleForm').reset();$('#articleId').value='';$('#date').value=new Date().toISOString().slice(0,10);$('#author').value='AFAQ JOOD Regulatory Intelligence Team';$('#impact').value='informational';$('#editorTitle').textContent='Create article';$('#editorStatus').textContent='Draft';$('#editorStatus').className='status draft';$('#imagePreview').textContent='No image selected';$('#revisionNote').value='';langs.forEach(l=>{$(`#title_${l}`).value='';$(`#summary_${l}`).value='';$(`#body_${l}`).innerHTML='';$(`#know_${l}`).value=''});$('#revisionHistory').textContent='No revisions yet.';$('#slug').value='';updateTranslationStatus();}
  function editArticle(id){const a=articles.find(x=>x.id===id);if(!a)return;editingId=id;$('#articleId').value=id;$('#countryCode').value=a.countryCode;$('#authority').value=a.authority||'';$('#category').value=a.category?.en||'Regulatory Update';$('#date').value=a.date||'';$('#author').value=a.author||'AFAQ JOOD Regulatory Intelligence Team';$('#impact').value=a.impact||'informational';$('#products').value=(a.products||[]).join(', ');$('#tags').value=(a.tags||[]).join(', ');$('#slug').value=a.slug||'';$('#featured').checked=!!a.featured;langs.forEach(l=>{$(`#title_${l}`).value=a.title?.[l]||'';$(`#summary_${l}`).value=a.summary?.[l]||'';$(`#body_${l}`).innerHTML=a.body?.[l]||'';$(`#know_${l}`).value=a.whatKnow?.[l]||''});renderRevisionHistory(a);$('#imageUrl').value=a.image||'';$('#sourceName').value=a.sourceName||'';$('#sourceUrl').value=a.sourceUrl||'';$('#sourceType').value=a.sourceType||'Official Regulatory Authority';$('#revisionNote').value='';$('#editorTitle').textContent='Edit article';$('#editorStatus').textContent=a.status||'Draft';$('#editorStatus').className=`status ${a.status==='published'?'published':'draft'}`;$('#imagePreview').innerHTML=a.image?`<img src="${esc(a.image)}" alt="">`:'No image selected';updateTranslationStatus();switchView('editor');}
  function categoryAr(v){return {'Regulatory Update':'تحديث تنظيمي','Type Approval':'موافقة نوعية','Technical Standards':'المعايير الفنية','Spectrum & RF':'الطيف الترددي وRF','Market Access':'دخول السوق','Compliance Alert':'تنبيه امتثال','AFAQ JOOD Update':'تحديث آفاق جود'}[v]||v}
  function categoryZh(v){return {'Regulatory Update':'法规更新','Type Approval':'型式认证','Technical Standards':'技术标准','Spectrum & RF':'频谱与RF','Market Access':'市场准入','Compliance Alert':'合规提醒','AFAQ JOOD Update':'AFAQ JOOD 更新'}[v]||v}
  function slugify(s){return String(s||'').toLowerCase().replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'article'}
  function uniqueSlug(base,id=''){let slug=slugify(base),candidate=slug,n=2;while(articles.some(a=>a.slug===candidate&&a.id!==id)){candidate=`${slug}-${n++}`}return candidate}
  function collect(status){const c=countries().find(x=>x.code===$('#countryCode').value)||{};const title={en:$('#title_en').value.trim(),ar:$('#title_ar').value.trim(),zh:$('#title_zh').value.trim()};const summary={en:$('#summary_en').value.trim(),ar:$('#summary_ar').value.trim(),zh:$('#summary_zh').value.trim()};const body={en:$('#body_en').innerHTML.trim(),ar:$('#body_ar').innerHTML.trim(),zh:$('#body_zh').innerHTML.trim()};const existing=editingId?articles.find(x=>x.id===editingId):null;const slug=existing?.slug||uniqueSlug(title.en,editingId);const whatKnow={en:$('#know_en').value.trim(),ar:$('#know_ar').value.trim(),zh:$('#know_zh').value.trim()};return {id:editingId||crypto.randomUUID(),slug,countryCode:c.code,country:c.name,countrySlug:slugify(c.name),countryName:{en:c.name,ar:localizedCountry(c.name,'ar'),zh:localizedCountry(c.name,'zh')},authority:$('#authority').value.trim(),category:{en:$('#category').value,ar:categoryAr($('#category').value),zh:categoryZh($('#category').value)},date:$('#date').value,author:$('#author').value.trim()||'AFAQ JOOD Regulatory Intelligence Team',impact:$('#impact').value,products:$('#products').value.split(',').map(x=>x.trim()).filter(Boolean),tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),title,summary,body,whatKnow,image:$('#imageUrl').value.trim()||null,sourceName:$('#sourceName').value.trim(),sourceUrl:$('#sourceUrl').value.trim(),sourceType:$('#sourceType').value,featured:$('#featured').checked,status,updatedAt:new Date().toISOString(),revisionNote:$('#revisionNote').value.trim()};}
  function validate(a,publishing){const missing=[];if(!a.countryCode)missing.push('country');if(!a.authority)missing.push('authority');if(!a.date)missing.push('date');for(const l of langs){if(!a.title[l])missing.push(`title (${l})`);if(publishing&&!a.body[l])missing.push(`article body (${l})`)}if(publishing&&!a.sourceUrl)missing.push('official source URL');return missing;}
  function renderRevisionHistory(a){const box=$('#revisionHistory');const r=Array.isArray(a?.revisions)?a.revisions.slice().reverse():[];box.innerHTML=r.length?r.map(x=>`<div class="revisionItem"><b>${esc(x.action||'update')}</b><span>${esc(String(x.at||'').slice(0,16).replace('T',' '))}</span><p>${esc(x.summary||'')}</p></div>`).join(''):'No revisions yet.';}
  function updateTranslationStatus(){const chips=langs.map(l=>{const ok=!!($('#title_'+l)?.value.trim()&&$('#body_'+l)?.innerText.trim());return `<span class="translationChip ${ok?'ok':'missing'}">${l.toUpperCase()} ${ok?'Complete':'Needs content'}</span>`}).join('');$('#translationStatus').innerHTML=`<div class="ey">Translation readiness</div><div class="translationChips">${chips}</div>`;}
  function saveLocalDraft(){const a=collect('draft'),i=articles.findIndex(x=>x.id===a.id);if(i>=0)articles[i]=a;else articles.unshift(a);saveDrafts();editingId=a.id;$('#editorStatus').textContent='Draft';$('#editorStatus').className='status draft';updateTranslationStatus();renderDashboard();alert('Draft saved locally.');}
  function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);let data=c.toDataURL('image/webp',.84);if(data.length>1200000)data=c.toDataURL('image/jpeg',.78);res(data)};img.onerror=rej;img.src=r.result};r.onerror=rej;r.readAsDataURL(file)});}
  async function publish(){const a=collect('published'),missing=validate(a,true);if(missing.length){alert('Please complete: '+missing.join(', '));return}const btn=$('#publishArticle');btn.disabled=true;btn.textContent='Publishing…';try{const payload={article:a};if(imageData){payload.image={base64:imageData.split(',')[1],path:`/assets/news/${a.countrySlug}/${a.slug}.webp`}}const r=await api('publish',payload);articles=r.articles||[];saveState('Published successfully');editingId=a.id;$('#editorStatus').textContent='Published';$('#editorStatus').className='status published';renderDashboard();renderList();alert('Published. Netlify will deploy the update after the GitHub commit.');}catch(e){alert('Publish failed: '+e.message)}finally{btn.disabled=false;btn.textContent='Publish';}}
  async function deleteArticle(){if(!editingId){alert('No article selected.');return}const a=articles.find(x=>x.id===editingId);if(!a)return;if(!confirm('Delete this article from AFAQ JOOD? This will remove it from the public site.'))return;if(a.status==='published'){try{const r=await api('delete',{id:a.id});articles=r.articles||[];saveState('Deleted from site');clearEditor();switchView('articles');alert('Article deleted and removed from the public site.')}catch(e){alert('Delete failed: '+e.message)}}else{articles=articles.filter(x=>x.id!==a.id);saveDrafts();clearEditor();switchView('articles');}}
  function preview(){const a=collect('draft');sessionStorage.setItem('afaqNewsPreview',JSON.stringify(a));window.open(`news-article.html?preview=1&slug=${encodeURIComponent(a.slug)}`,'_blank','noopener');}
  function toolbar(){$$('.toolbar button').forEach(b=>b.addEventListener('click',()=>{const cmd=b.dataset.cmd;if(cmd==='createLink'){const url=prompt('URL');if(url)document.execCommand('createLink',false,url)}else if(cmd==='formatBlock')document.execCommand(cmd,false,b.dataset.value);else document.execCommand(cmd,false,null);updateTranslationStatus()}));}
  async function init(){fillCountries();loadDrafts();toolbar();clearEditor();$('#newArticleBtn').onclick=()=>{clearEditor();switchView('editor')};$('#newArticleBtn2').onclick=()=>{clearEditor();switchView('editor')};$$('.adminSide nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-view="articles"]').forEach(b=>b.addEventListener('click',()=>switchView('articles')));$('#saveDraft').onclick=saveLocalDraft;$('#publishArticle').onclick=publish;$('#deleteArticle').onclick=deleteArticle;$('#previewArticle').onclick=preview;$('#siteUrl').value=localStorage.getItem(SITE_URL_KEY)||'';$('#saveSiteUrl').onclick=async()=>{const u=$('#siteUrl').value.trim().replace(/\/$/,'');if(!/^https:\/\//i.test(u)){$('#apiStatus').textContent='Enter a valid HTTPS Netlify site URL.';return}localStorage.setItem(SITE_URL_KEY,u);try{const r=await api('test');$('#apiStatus').textContent=`Connected. ${r.articles} published articles.`;await sync()}catch(e){$('#apiStatus').textContent=e.message}};$('#testApi').onclick=async()=>{try{const r=await api('test');$('#apiStatus').textContent=`Connected. ${r.articles} published articles.`}catch(e){$('#apiStatus').textContent=e.message}};$('#imageFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;imageName=f.name;imageData=await fileToData(f);$('#imagePreview').innerHTML=`<img src="${imageData}" alt="">`});$$('.languageTabs button').forEach(b=>b.addEventListener('click',()=>{$$('.languageTabs button').forEach(x=>x.classList.toggle('active',x===b));$$('[data-lang-panel]').forEach(x=>x.classList.toggle('hidden',x.dataset.langPanel!==b.dataset.editorLang))}));langs.forEach(l=>{$(`#title_${l}`).addEventListener('input',updateTranslationStatus);$(`#body_${l}`).addEventListener('input',updateTranslationStatus)});$('#title_en').addEventListener('input',()=>{if(!editingId)$('#slug').value=uniqueSlug($('#title_en').value)});['adminSearch','adminCountryFilter','adminStatusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderList));document.addEventListener('click',async e=>{const ed=e.target.closest('[data-edit]');if(ed)editArticle(ed.dataset.edit);const del=e.target.closest('[data-delete]');if(del){editingId=del.dataset.delete;await deleteArticle()}const op=e.target.closest('[data-open]');if(op){const a=articles.find(x=>x.id===op.dataset.open);if(a)window.open(`/news-article.html?slug=${encodeURIComponent(a.slug)}`,'_blank','noopener')}const cp=e.target.closest('[data-media-copy]');if(cp){try{await navigator.clipboard.writeText(cp.dataset.mediaCopy);cp.textContent='Copied';setTimeout(()=>cp.textContent='Copy path',1200)}catch{}}})
  }
  init();
})();
