(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CFG="afaqNewsGithubConfig",DRAFTS="afaqNewsLocalDrafts",SITE="https://afaqjood.com";let articles=[],editing=null,imageFile=null,originalImage=null,draftImageData=null,countries=[];
const state=()=>{try{return JSON.parse(localStorage.getItem(CFG)||"{}")}catch{return{}}};
const token=()=>sessionStorage.getItem("afaqNewsGithubToken")||"";
const saveState=m=>{if($("#status"))$("#status").textContent=m};
const api=async(path,opts={})=>{const t=token();if(!t)throw Error("يرجى الاتصال بـ GitHub أولاً.");const r=await fetch("https://api.github.com/repos/"+encodeURIComponent(state().owner)+"/"+encodeURIComponent(state().repo)+"/"+path,{...opts,headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+t,"X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(opts.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.message||("GitHub API "+r.status));return j};
const branch=()=>state().branch||"main";
const bytes64=bytes=>{let out="";for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.slice(i,i+0x8000));return btoa(out)};
async function file(path){try{return await api("contents/"+path+"?ref="+encodeURIComponent(branch()))}catch(e){if(String(e.message).includes("Not Found"))return null;throw e}}
async function gitTree(changes,message){const ref=await api("git/ref/heads/"+encodeURIComponent(branch()));const commit=await api("git/commits/"+ref.object.sha);const tree=[];for(const c of changes){if(c.delete){tree.push({path:c.path,mode:"100644",type:"blob",sha:null});continue}const blob=await api("git/blobs",{method:"POST",body:JSON.stringify({content:c.content,encoding:c.encoding||"utf-8"})});tree.push({path:c.path,mode:"100644",type:"blob",sha:blob.sha})}const tr=await api("git/trees",{method:"POST",body:JSON.stringify({base_tree:commit.tree.sha,tree})});const nc=await api("git/commits",{method:"POST",body:JSON.stringify({message,tree:tr.sha,parents:[ref.object.sha]})});await api("git/refs/heads/"+encodeURIComponent(branch()),{method:"PATCH",body:JSON.stringify({sha:nc.sha,force:false})});return nc.sha}
function slugify(s){return String(s||"").toLowerCase().trim().normalize("NFKD").replace(/[^\w\s-]/g,"").replace(/_/g,"-").replace(/\s+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"article"}
function uniqueSlug(base,id){let s=slugify(base)||"article",n=2;while(articles.some(a=>a.slug===s&&a.id!==id)){s=slugify(base)+"-"+n++}return s}
function today(){return new Date().toISOString().slice(0,10)}
function cleanText(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function textToHtml(s){return String(s||"").split(/\n{2,}/).map(p=>`<p>${cleanText(p).replace(/\n/g,"<br>")}</p>`).join("")}
function htmlToText(s){return String(s||"").replace(/<br\s*\/?>(\n)?/gi,"\n").replace(/<\/p>\s*<p>/gi,"\n\n").replace(/<[^>]+>/g,"")}
function countryKey(c,i){return `${c.code}__${slugify(c.name)}__${i}`}
function localizedCountry(name){const ar={'United Arab Emirates':'الإمارات العربية المتحدة','Saudi Arabia':'السعودية','Qatar':'قطر','Kuwait':'الكويت','Oman':'عُمان','Bahrain':'البحرين','Jordan':'الأردن','Iraq':'العراق','Lebanon':'لبنان','Palestine – West Bank':'فلسطين – الضفة الغربية','Palestine – Gaza':'فلسطين – غزة','Syria':'سوريا','Yemen – Aden':'اليمن – عدن',"Yemen – Sana'a":'اليمن – صنعاء','Iran':'إيران','Turkey':'تركيا','Algeria':'الجزائر','Egypt':'مصر','Libya':'ليبيا','Morocco':'المغرب','Sudan':'السودان','Tunisia':'تونس','Mauritania':'موريتانيا','Angola':'أنغولا','Botswana':'بوتسوانا','Djibouti':'جيبوتي','Kenya':'كينيا','Malawi':'مالاوي','Mauritius':'موريشيوس','Namibia':'ناميبيا','Nigeria':'نيجيريا','South Africa':'جنوب أفريقيا','Tanzania':'تنزانيا','Uganda':'أوغندا','Ethiopia':'إثيوبيا','Ghana':'غانا',"Côte d'Ivoire":'ساحل العاج','Senegal':'السنغال'};return ar[name]||name}
async function loadCountries(){try{const r=await fetch("countries.json",{cache:"no-store"});countries=await r.json();if(!Array.isArray(countries))countries=[]}catch{countries=[]}const s=$("#country"),f=$("#countryFilter");const middle=countries.filter(c=>c.region==='Middle East'),africa=countries.filter(c=>c.region==='Africa');s.innerHTML='<option value="">اختر الدولة</option>'+[['الشرق الأوسط',middle],['أفريقيا',africa]].map(([label,list])=>`<optgroup label="${label}">${list.map((c,i)=>{const idx=countries.indexOf(c);return `<option value="${cleanText(countryKey(c,idx))}">${cleanText(c.flag||'')} ${cleanText(localizedCountry(c.name))}</option>`}).join('')}</optgroup>`).join('');f.innerHTML='<option value="">جميع الدول</option>'+countries.map((c,i)=>`<option value="${cleanText(countryKey(c,i))}">${cleanText(c.flag||'')} ${cleanText(localizedCountry(c.name))}</option>`).join('')}
function selectedCountry(){const k=$("#country").value;return countries.find((c,i)=>countryKey(c,i)===k)||null}
function formData(status="draft"){const id=editing?.id||("news-"+Date.now()),c=selectedCountry(),titleEn=$("#title_en").value.trim(),slug=editing?.slug||uniqueSlug(titleEn,id),base=editing||{};return{id,slug,status,country:c?.name||base.country||"",countryCode:c?.code||base.countryCode||"",countryKey:c?countryKey(c,countries.indexOf(c)):(base.countryKey||""),countrySlug:c?slugify(c.name):(base.countrySlug||""),countryName:{...(base.countryName||{}),en:c?.name||base.countryName?.en||base.country||""},authority:c?.authority||$("#authority").value.trim()||base.authority||"",category:$("#category").value,date:$("#date").value,publishedAt:status==="published"?(base.publishedAt||new Date().toISOString()):base.publishedAt||null,updatedAt:new Date().toISOString(),author:$("#author").value.trim()||base.author||"AFAQ JOOD Regulatory Intelligence Team",impact:$("#impact").value,featured:$("#featured").checked,products:$("#products").value.split(",").map(x=>x.trim()).filter(Boolean),tags:$("#tags").value.split(",").map(x=>x.trim()).filter(Boolean),title:{...(base.title||{}),en:titleEn},summary:{...(base.summary||{}),en:$("#summary_en").value.trim()},body:{...(base.body||{}),en:textToHtml($("#body_en").value)},whatKnow:{...(base.whatKnow||{}),en:textToHtml($("#know_en").value)},sourceName:$("#sourceName").value.trim()||base.sourceName||"",sourceUrl:$("#sourceUrl").value.trim()||base.sourceUrl||"",sourceType:$("#sourceType").value||base.sourceType||"Official Regulatory Authority",image:editing?.image||"",draftImageData:draftImageData||editing?.draftImageData||null}}
async function loadTemplate(){const r=await fetch("article-template.html",{cache:"no-store"});window.__ARTICLE_TEMPLATE=await r.text()}
function articleHTML(a){let tpl=window.__ARTICLE_TEMPLATE||"";const title=a.title?.en||"Regulatory Update | AFAQ JOOD";tpl=tpl.replace(/<title>.*?<\/title>/i,`<title>${cleanText(title)} | AFAQ JOOD</title>`);return tpl.replace("</body>",`<script>window.__AFAQ_STATIC_ARTICLE=${JSON.stringify(a).replace(/</g,"\\u003c")};</script></body>`)}
function fill(a){editing=a;const cIndex=countries.findIndex(c=>c.code===a.countryCode&&c.name===a.country);$("#country").value=a.countryKey||(cIndex>=0?countryKey(countries[cIndex],cIndex):"");$("#authority").value=(cIndex>=0?countries[cIndex].authority:(a.authority||""));$("#category").value=a.category||"Regulatory Update";$("#date").value=a.date||today();$("#author").value=a.author||"AFAQ JOOD Regulatory Intelligence Team";$("#impact").value=a.impact||"informational";$("#featured").checked=!!a.featured;$("#products").value=(a.products||[]).join(", ");$("#tags").value=(a.tags||[]).join(", ");$("#slug").value=a.slug||"";$("#title_en").value=a.title?.en||"";$("#summary_en").value=a.summary?.en||"";$("#body_en").value=htmlToText(a.body?.en);$("#know_en").value=htmlToText(a.whatKnow?.en);$("#sourceName").value=a.sourceName||"";$("#sourceUrl").value=a.sourceUrl||"";$("#editorHeading").textContent="تعديل الخبر";$("#editorStatus").textContent=a.status==="published"?"منشور":"في الأرشيف";$("#editorStatus").className="badge "+(a.status||"draft");originalImage=a.image||null;draftImageData=a.draftImageData||null;$("#imagePreview").innerHTML=a.image?`<img src="${cleanText(mediaUrl(a.image))}" alt="">`:a.draftImageData?`<img src="${cleanText(a.draftImageData)}" alt="">`:"لم يتم اختيار صورة"}
function clearForm(){editing=null;imageFile=null;originalImage=null;draftImageData=null;$("#form").reset();$("#date").value=today();$("#author").value="AFAQ JOOD Regulatory Intelligence Team";$("#slug").value="";$("#authority").value="";$("#editorHeading").textContent="إنشاء خبر جديد";$("#editorStatus").textContent="في الأرشيف";$("#editorStatus").className="badge draft";$("#imagePreview").textContent="لم يتم اختيار صورة"}
async function getArticles(){let remote=[];const f=await file("news.json");if(f){try{const raw=decodeURIComponent(escape(atob(f.content.replace(/\n/g,""))));remote=JSON.parse(raw);if(!Array.isArray(remote))remote=[]}catch{try{remote=JSON.parse(atob(f.content.replace(/\n/g,"")))}catch{remote=[]}}}let drafts=[];try{drafts=JSON.parse(localStorage.getItem(DRAFTS)||"[]");if(!Array.isArray(drafts))drafts=[]}catch{drafts=[]}const ids=new Set(remote.map(a=>a.id));articles=[...remote,...drafts.filter(a=>!ids.has(a.id))]}
async function refresh(){await getArticles();draw();saveState(`تمت المزامنة · ${articles.filter(a=>a.status!=="draft").length} خبراً منشوراً · ${articles.filter(a=>a.status==="draft").length} في الأرشيف`)}
function mediaUrl(src){const s=String(src||"");if(!s)return SITE+"/assets/afaq-jood-logo.png";if(/^https?:\/\//i.test(s))return s;return SITE+"/"+s.replace(/^\/+/,"")}
function row(a){return `<div class="articleRow"><img class="thumb" src="${cleanText(mediaUrl(a.image))}"><div><h3>${cleanText(a.title?.en||"خبر بدون عنوان")}</h3><div class="meta">${cleanText(localizedCountry(a.country||""))} · ${cleanText(a.date||"")} · <b>${a.status==="draft"?"مسودة":"منشور"}</b><br><span dir="ltr">/news/${cleanText(a.slug||"")}/</span></div></div><div class="rowActions"><button data-edit="${cleanText(a.id)}">تعديل</button>${a.status!=="draft"?`<button data-open="${cleanText(a.slug)}">فتح</button>`:""}<button class="del" data-delete="${cleanText(a.id)}">حذف</button></div></div>`}
function draw(){const published=articles.filter(a=>a.status!=="draft"),draft=articles.filter(a=>a.status==="draft");$("#pubCount").textContent=published.length;$("#draftCount").textContent=draft.length;$("#featCount").textContent=articles.filter(a=>a.featured).length;$("#marketCount").textContent=new Set(articles.map(a=>a.countryCode||a.country).filter(Boolean)).size;$("#recent").innerHTML=articles.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8).map(row).join("")||'<div class="empty">لا توجد أخبار بعد.</div>';drawList()}
function drawList(){const q=($("#search")?.value||"").toLowerCase(),s=$("#statusFilter")?.value||"",c=$("#countryFilter")?.value||"";const x=articles.filter(a=>!s||a.status===s).filter(a=>!c||a.countryKey===c||(a.countryCode&&countries.some((z,i)=>countryKey(z,i)===c&&z.code===a.countryCode))).filter(a=>[a.title?.en,a.country,a.authority,a.category].join(" ").toLowerCase().includes(q));$("#list").innerHTML=x.map(row).join("")||'<div class="empty">لا توجد أخبار مطابقة للبحث.</div>'}
function view(v){$$('.view').forEach(x=>x.classList.add('hidden'));$("#"+v).classList.remove('hidden');$$('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$("#heading").textContent={dashboard:"لوحة الأخبار",articles:"جميع الأخبار",editor:editing?"تعديل الخبر":"إنشاء خبر جديد",settings:"إعدادات النشر"}[v];if(v==="articles")drawList();if(v==="dashboard")draw()}
async function compress(file){return new Promise((res,rej)=>{const im=new Image(),fr=new FileReader();fr.onload=()=>im.src=fr.result;fr.onerror=rej;im.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext("2d").drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{if(!b)return rej(Error("تعذر تجهيز الصورة"));const r=new FileReader();r.onload=()=>res({bytes:new Uint8Array(r.result)});r.readAsArrayBuffer(b)},"image/jpeg",.82)};fr.readAsDataURL(file)})}
function bind(){$("#newBtn").onclick=()=>{clearForm();view("editor")};$("#newBtn2").onclick=()=>{clearForm();view("editor")};$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$("#search").oninput=drawList;$("#statusFilter").onchange=drawList;$("#countryFilter").onchange=drawList;$("#country").onchange=()=>{const c=selectedCountry();$("#authority").value=c?.authority||"";};$("#title_en").oninput=()=>{if(!editing)$("#slug").value=uniqueSlug($("#title_en").value,"")};$("#image").onchange=e=>{imageFile=e.target.files[0];draftImageData=null;if(imageFile){const u=URL.createObjectURL(imageFile);$("#imagePreview").innerHTML=`<img src="${u}" alt="">`}};
$("#connect").onclick=async e=>{e.preventDefault();const c={owner:$("#owner").value.trim(),repo:$("#repo").value.trim(),branch:$("#branch").value.trim()||"main"};const t=$("#token").value.trim();if(!t){$("#connection").textContent="أدخل مفتاح GitHub أولاً.";return}sessionStorage.setItem("afaqNewsGithubToken",t);localStorage.setItem(CFG,JSON.stringify(c));try{const r=await api("branches/"+encodeURIComponent(c.branch));$("#connection").textContent="تم الاتصال بنجاح ✓ · الفرع: "+r.name;saveState("تم الاتصال بـ GitHub");await refresh()}catch(err){sessionStorage.removeItem("afaqNewsGithubToken");$("#connection").textContent="تعذر الاتصال: "+err.message;saveState("فشل الاتصال")}};
$("#syncNow").onclick=async()=>{try{saveState("جاري مزامنة الأخبار…");await refresh()}catch(err){alert(err.message)}};$("#clearToken").onclick=()=>{sessionStorage.removeItem("afaqNewsGithubToken");$("#connection").textContent="تم مسح المفتاح من هذه الجلسة.";saveState("تم مسح المفتاح")};
$("#preview").onclick=()=>{const a=formData("published");if(!a.title.en)return alert("اكتب عنوان الخبر أولاً.");sessionStorage.setItem("afaqNewsPreview",JSON.stringify(a));window.open("article-template.html?preview=1&slug="+encodeURIComponent(a.slug),"_blank")};
$("#saveDraft").onclick=async()=>{try{const a=formData("draft");if(!a.countryCode)return alert("اختر الدولة أولاً.");if(!a.date)return alert("اختر تاريخ الخبر أولاً.");if(!a.title.en)return alert("اكتب عنوان الخبر بالإنجليزية أولاً.");if(!$("#body_en").value.trim())return alert("اكتب محتوى الخبر أولاً.");if(imageFile instanceof File){const im=await compress(imageFile);a.draftImageData="data:image/jpeg;base64,"+bytes64(im.bytes);a.image="";}articles=articles.filter(x=>x.id!==a.id).concat(a);localStorage.setItem(DRAFTS,JSON.stringify(articles.filter(x=>x.status==="draft")));editing=a;draftImageData=a.draftImageData||null;imageFile=null;saveState("تم حفظ الخبر في الأرشيف ✓");draw();view("articles")}catch(e){alert(e.message)}};$("#publishAll").onclick=publishAllDrafts;
$("#publish").onclick=async()=>{try{const a=formData("published");const missing=[];if(!a.countryCode)missing.push("الدولة");if(!a.date)missing.push("تاريخ النشر");if(!a.title.en)missing.push("عنوان الخبر بالإنجليزية");if(!$("#body_en").value.trim())missing.push("محتوى الخبر");if(missing.length)throw Error("يرجى استكمال: "+missing.join("، "));saveState("جاري تجهيز الخبر للنشر…");if(imageFile instanceof File){const im=await compress(imageFile);a.image="/assets/news/"+a.countryCode.toLowerCase()+"/"+a.slug+".jpg";imageFile={...im,path:a.image.replace(/^\//,"")}}else if(draftImageData){a.image="/assets/news/"+a.countryCode.toLowerCase()+"/"+a.slug+".jpg";imageFile={bytes:dataUrlToBytes(draftImageData),path:a.image.replace(/^\//,"")}}else a.image=originalImage||"";delete a.draftImageData;const next=articles.filter(x=>x.id!==a.id).concat(a),changes=[{path:"news.json",content:JSON.stringify(next,null,2)}];if(imageFile)changes.push({path:imageFile.path,content:bytes64(imageFile.bytes),encoding:"base64"});if(editing?.image&&editing.image!==a.image&&editing.image.startsWith("/assets/news/"))changes.push({path:editing.image.replace(/^\/+/,""),delete:true});saveState("جاري النشر إلى GitHub…");await gitTree(changes,"Publish news: "+a.title.en);articles=next;localStorage.setItem(DRAFTS,JSON.stringify(articles.filter(x=>x.status==="draft")));originalImage=a.image;imageFile=null;draftImageData=null;editing=a;$("#editorStatus").textContent="منشور";$("#editorStatus").className="badge published";saveState("تم النشر بنجاح ✓ · Netlify سيحدث الموقع تلقائياً");draw();alert("تم نشر الخبر بنجاح. سيقوم Netlify بتحديث الموقع تلقائياً.")}catch(e){saveState("تعذر النشر");alert(e.message)}};
function dataUrlToBytes(dataUrl){const b64=String(dataUrl).split(",")[1]||"";const bin=atob(b64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}
async function publishAllDrafts(){const drafts=articles.filter(a=>a.status==="draft");if(!drafts.length)return alert("لا توجد أخبار محفوظة في الأرشيف للنشر.");const invalid=drafts.filter(a=>!a.countryCode||!a.date||!a.title?.en||!htmlToText(a.body?.en).trim());if(invalid.length){const names=invalid.map(a=>a.title?.en||"خبر بدون عنوان").slice(0,8);return alert("يوجد أخبار ناقصة ولن يتم نشر الدفعة حتى تكتمل:\n\n"+names.join("\n")+"\n\nالمطلوب لكل خبر: الدولة، التاريخ، العنوان، ومحتوى الخبر.")}if(!confirm(`سيتم نشر ${drafts.length} خبراً دفعة واحدة. هل تريد المتابعة؟`))return;try{$("#publishAll").disabled=true;saveState(`جاري تجهيز ${drafts.length} أخبار للنشر…`);const draftIds=new Set(drafts.map(d=>d.id));const next=articles.map(a=>{if(!draftIds.has(a.id))return a;const x={...a,status:"published",publishedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(x.draftImageData&&!x.image)x.image="/assets/news/"+x.countryCode.toLowerCase()+"/"+x.slug+".jpg";delete x.draftImageData;return x});const changes=[{path:"news.json",content:JSON.stringify(next,null,2)}];for(const original of drafts){const x=next.find(a=>a.id===original.id);if(!x)continue;if(original.draftImageData){const bytes=dataUrlToBytes(original.draftImageData);changes.push({path:x.image.replace(/^\//,""),content:bytes64(bytes),encoding:"base64"});}}saveState("جاري نشر جميع الأخبار إلى GitHub…");await gitTree(changes,"Publish archived news batch: "+drafts.length+" articles");articles=next;localStorage.setItem(DRAFTS,JSON.stringify([]));draw();saveState(`تم نشر ${drafts.length} أخبار بنجاح ✓ · Netlify سيحدث الموقع تلقائياً`);alert(`تم نشر ${drafts.length} أخبار بنجاح. سيقوم Netlify بتحديث الموقع تلقائياً.`)}catch(e){saveState("تعذر نشر الدفعة");alert(e.message)}finally{$("#publishAll").disabled=false}}
$("#delete").onclick=async()=>{if(!editing)return alert("افتح خبراً موجوداً أولاً.");if(!confirm("هل أنت متأكد من حذف هذا الخبر؟ سيتم حذفه أيضاً من الموقع العام."))return;try{saveState("جاري الحذف…");const next=articles.filter(x=>x.id!==editing.id),changes=[{path:"news.json",content:JSON.stringify(next,null,2)}];if(editing.image&&editing.image.startsWith("/assets/news/"))changes.push({path:editing.image.replace(/^\/+/,""),delete:true});await gitTree(changes,"Delete news: "+(editing.title?.en||editing.slug));articles=next;localStorage.setItem(DRAFTS,JSON.stringify(articles.filter(x=>x.status==="draft")));clearForm();view("articles");saveState("تم حذف الخبر بنجاح ✓")}catch(e){saveState("تعذر الحذف");alert(e.message)}};
document.addEventListener("click",e=>{const b=e.target.closest("[data-edit],[data-delete],[data-open]");if(!b)return;if(b.dataset.edit){const a=articles.find(x=>x.id===b.dataset.edit);if(a){fill(a);view("editor")}}if(b.dataset.delete){const a=articles.find(x=>x.id===b.dataset.delete);if(a){editing=a;fill(a);$("#delete").click()}}if(b.dataset.open){window.open("/news-article.html?slug="+encodeURIComponent(b.dataset.open),"_blank")}})}
async function boot(){await loadCountries();const c=state();$("#owner").value=c.owner||"aymnalmmry06-art";$("#repo").value=c.repo||"Testing";$("#branch").value=c.branch||"main";await loadTemplate();bind();if(token()){$("#connection").textContent="مفتاح GitHub موجود في جلسة المتصفح.";try{await refresh();setInterval(()=>{refresh().catch(()=>{})},60000)}catch{saveState("تحقق من اتصال GitHub")}}else saveState("جاهز — ابدأ من إعدادات النشر")}
boot();})();
